sudo: false

os: linux

dist: xenial

language: ruby

rvm:
  - '2.4'
  - '2.5'
  - '2.6'
  - '2.7'

matrix:
  fast_finish:
    true

notifications:
  email: false

addons:
  apt:
    packages:
      - libopenblas-dev
      - liblapacke-dev

before_install:
  - gem install --no-document bundler -v '~> 2.0'

install:
  - gem install specific_install
  - gem specific_install https://github.com/ruby-numo/numo-narray
  - bundle install --jobs=3 --retry=3

script:
  - gem build numo-linalg.gemspec
  - gem install numo-linalg-*.gem
  - rspec --format documentation spec
